# Generated by Django 3.0.8 on 2020-07-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_id', models.IntegerField()),
                ('head_commit', models.CharField(max_length=40)),
                ('is_merged', models.BooleanField(default=False)),
            ],
        ),
    ]
